FROM python:3.11-slim

WORKDIR /app

# system deps for SQLite + build tools if needed
RUN apt-get update && apt-get install -y build-essential libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./
# copy additional files if you have stress_test or others
COPY stress_test.py ./

ENV FLASK_ENV=production
EXPOSE 5000

CMD ["python", "app.py"]
